extends Node
## Centralized translation service.
## Usage: Tr.t("KEY"), Tr.res_name("gold"), Tr.res_upper("gold")
## Change locale with Tr.set_locale("en")

var _locale := "es"

const _RESOURCES := {
	"es": {"gold": "oro", "steel": "acero", "oil": "petroleo", "wood": "madera"},
	"en": {"gold": "gold", "steel": "steel", "oil": "oil", "wood": "wood"},
}

const _RESOURCES_UPPER := {
	"es": {"gold": "ORO", "steel": "ACERO", "oil": "PETROLEO", "wood": "MADERA"},
	"en": {"gold": "GOLD", "steel": "STEEL", "oil": "OIL", "wood": "WOOD"},
}

const _RESOURCES_CAP := {
	"es": {"gold": "Oro", "steel": "Acero", "oil": "Petroleo", "wood": "Madera"},
	"en": {"gold": "Gold", "steel": "Steel", "oil": "Oil", "wood": "Wood"},
}

const _STRINGS := {
	"es": {
		# Buttons
		"BTN_BUILD": "CONSTRUIR",
		"BTN_CLOSE": "Cerrar",
		"BTN_MOVE": "Mover",
		"BTN_DEMOLISH": "Demoler",
		"BTN_RENAME": "Renombrar",
		"BTN_CLEAR": "LIMPIAR",
		"BTN_UPGRADE": "Mejorar",
		"BTN_CONFIRM": "Confirmar",
		"BTN_CANCEL": "Cancelar",
		"CONFIRM_NEW_GAME": "Esto borrara tu partida actual y empezara de cero. No se puede deshacer.",
		"LBL_SETTINGS_GAME": "PARTIDA",

		# Labels
		"LBL_ACTIONS": "Acciones",
		"LBL_NO_ACTIONS": "Sin acciones disponibles",
		"LBL_BUILDINGS_AVAILABLE": "Edificios disponibles",
		"LBL_BUILDING_NAME_PLACEHOLDER": "Nombre del edificio...",
		"LBL_FREE": "Gratis",
		"LBL_NATURAL_RESOURCE": "Recurso natural disponible para extraccion.",
		"LBL_LEVEL": "Nivel %d",
		"LBL_MAX_LEVEL": "Nivel maximo",
		"LBL_UPGRADE_TO": "Mejorar a Nivel %d",
		"LBL_STORAGE_CAP": "Almacenamiento: %d/%d",
		"LBL_LIMIT_REACHED": "Limite alcanzado (%d/%d)",
		"LBL_REQUIRES": "Requiere: %s",
		"LBL_REQUIRES_DEPOSIT": "Debe colocarse sobre un deposito de petroleo",
		"LBL_NEEDS_FOREST_NEAR": "El aserradero necesita un bosque al lado",
		"LBL_NEEDS_GOLD_VEIN_NEAR": "La mina de oro necesita una veta de oro al lado",
		"LBL_NEEDS_IRON_NEAR": "La fundicion necesita un yacimiento de hierro al lado",
		"LBL_STATUS_IDLE": "Zzz",
		"LBL_NOT_ENOUGH_RESOURCES": "Recursos insuficientes!",
		"LBL_UPGRADE_COMPLETE": "Mejora completa!",

		# Formats
		"FMT_COST": "Costo: %s",
		"FMT_PRODUCES": "Produce: %s",
		"FMT_PRODUCES_EVERY": "Produce: %s cada %ds",
		"FMT_PROGRESS": "%s — %ds restantes",
		"FMT_CONSTRUCTION": "En construccion: %d%% — %ds restantes",
		"FMT_CONSTRUCTING": "Construyendo %d%%",
		"FMT_UPGRADING": "Mejorando %d%%",
		"FMT_CONSTRUCTION_COMPLETE": "Construccion completa!",
		"FMT_DURATION": "Duracion: %ds",
		"FMT_OFFLINE_TITLE": "Mientras estuviste fuera (%s)",
		"FMT_DEMOLISH_CONFIRM": "Demoler %s?\nReembolso: %d%%",
		"LBL_DEPOSIT_USES": "%d usos restantes",
		"LBL_DEPOSIT_DEPLETED": "Deposito agotado!",

		# Deposits
		"DEP_GOLD_VEIN": "Veta de Oro",
		"DEP_IRON": "Hierro",
		"DEP_OIL": "Petroleo",
		"DEP_FOREST": "Bosque",

		# Processes - Nucleo
		"PROC_WOOD_PLANKS": "Laminas de Madera",
		"PROC_IRON_SHEETS": "Laminas de Hierro",
		"PROC_WATER_PIPES": "Tubos de Agua",
		# Processes - Sawmill
		"PROC_REFINED_LUMBER": "Madera Refinada",
		"PROC_CHARCOAL": "Carbon Vegetal",
		# Processes - Gold Mine
		"PROC_DEEP_MINING": "Mineria Profunda",
		"PROC_GEM_EXTRACTION": "Extraccion de Gemas",
		# Processes - Foundry
		"PROC_ALLOY_SMELTING": "Fundicion de Aleacion",
		"PROC_ARMOR_PLATES": "Placas de Armadura",
		# Processes - Refinery
		"PROC_FUEL_DISTILLATION": "Destilacion de Combustible",
		"PROC_CHEMICAL_PROCESSING": "Procesamiento Quimico",
		# Mining
		"PROC_MINE_GOLD": "Minar Oro",
		"PROC_MINE_IRON": "Minar Hierro",
		"PROC_MINE_OIL": "Extraer Petroleo",
		"PROC_MINE_WOOD": "Talar Arboles",

		# Market
		"BTN_MARKET": "MERCADO",
		"BTN_BUY": "Comprar",
		"BTN_SELL": "Vender",
		"LBL_MARKET_TITLE": "Mercado Imperial",
		"LBL_RESOURCE": "Recurso",
		"LBL_BUY_PRICE": "Compra",
		"LBL_SELL_PRICE": "Venta",
		"LBL_AMOUNT": "Cant.",
		"LBL_YOUR_GOLD": "Tu oro: %d",

		# Progression
		"BTN_PROGRESS": "PROGRESO",
		"LBL_PROGRESS_TITLE": "Progreso Imperial",
		"LBL_CURRENT_ERA": "Era actual",

		# Eras
		"ERA_FRONTIER": "Frontera",
		"ERA_INDUSTRIAL": "Industrial",
		"ERA_PETROLEUM": "Petrolera",

		# Milestones
		"MILE_PIONEER": "Pionero — Construir Aserradero",
		"MILE_PROSPECTOR": "Buscador — Construir Mina de Oro",
		"MILE_STOCKPILER": "Almacenista — Construir Deposito",
		"MILE_INDUSTRIALIST": "Industrialista — Construir Fundicion",
		"MILE_OIL_BARON": "Baron del Petroleo — Construir Refineria",
		"MILE_MERCHANT": "Mercader — 10 intercambios",
		"MILE_COMMANDER": "Comandante — Cuartel + 2 Torres",
		"MILE_GENERAL": "General — Construir Cuartel General",
		"MILE_VICTORY": "Victoria Imperial — Cuartel General Nv.3",
		"FMT_MILESTONE_COMPLETE": "Hito completado: %s",
		"FMT_ERA_UNLOCKED": "Nueva era: %s",

		# Victory
		"LBL_VICTORY_TITLE": "VICTORIA IMPERIAL",
		"LBL_VICTORY_SUBTITLE": "Tu imperio dieselpunk ha alcanzado la cima del poder. La tormenta es tuya.",
		"LBL_STAT_TIME": "Tiempo jugado:",
		"LBL_STAT_BUILDINGS": "Edificios construidos:",
		"LBL_STAT_TRADES": "Intercambios:",
		"LBL_STAT_MILESTONES": "Hitos completados:",
		"BTN_CONTINUE": "Seguir jugando",
		"BTN_NEW_GAME": "Nueva partida",

		# Locked resources
		"LBL_LOCKED_RESOURCE": "Recurso bloqueado",
		"LBL_DEPOSIT_LOCKED": "Recurso aun no desbloqueado. Avanza de era para acceder.",

		# Population & Workers
		"LBL_POPULATION": "Poblacion: %d/%d",
		"LBL_WORKERS": "Trabajadores: %d/%d",
		"LBL_MORALE": "Moral: %d%%",
		"LBL_WORKERS_NEEDED": "Requiere %d trabajadores",
		"LBL_NO_WORKERS": "Sin trabajadores disponibles",
		"LBL_NO_WORKERS_SHORT": "SIN TRABAJADORES",
		"NOTIF_POP_GREW": "Poblacion crecio: %d/%d",
		"NOTIF_NO_WOOD": "Falta madera para la poblacion!",
		"NOTIF_NO_GOLD": "Falta oro para pagar salarios!",
		"NOTIF_LOW_MORALE": "La moral esta muy baja! Produccion reducida.",
		"NOTIF_BUILT": "%s construido!",
		"NOTIF_UPGRADE_DONE": "%s mejorado a Nv.%d!",
		"NOTIF_DEPOSIT_GONE": "%s agotado.",

		# Notifications / Log
		"BTN_LOG": "LOG",
		"LBL_LOG_TITLE": "Registro de Actividad",

		# Random Events
		"EVENT_STORM": "Tormenta",
		"EVENT_STORM_DESC": "Vientos fuertes danan las reservas de madera.",
		"EVENT_RESOURCE_FIND": "Hallazgo de Recursos",
		"EVENT_RESOURCE_FIND_DESC": "Exploradores encuentran recursos abandonados.",
		"EVENT_MINING_ACCIDENT": "Accidente Minero",
		"EVENT_MINING_ACCIDENT_DESC": "Un derrumbe en la mina. Pierdes un trabajador.",
		"EVENT_TRADE_CARAVAN": "Caravana Comercial",
		"EVENT_TRADE_CARAVAN_DESC": "Una caravana pasa por tu base y deja oro.",
		"EVENT_FESTIVAL": "Festival Popular",
		"EVENT_FESTIVAL_DESC": "Los habitantes celebran. Gran impulso a la moral.",
		"EVENT_PLAGUE": "Plaga",
		"EVENT_PLAGUE_DESC": "Una enfermedad se extiende. Moral cae drasticamente.",
		"EVENT_PLAGUE_OVER": "La plaga ha pasado.",
		"EVENT_GOOD_HARVEST": "Buena Cosecha",
		"EVENT_GOOD_HARVEST_DESC": "Los bosques cercanos dan madera extra.",
		"EVENT_BANDIT_RAID": "Ataque de Bandidos",
		"EVENT_BANDIT_RAID_DESC": "Bandidos saquean parte de tu oro.",

		# Tech Tree
		"BTN_TECH": "TECNOLOGIA",
		"LBL_TECH_TITLE": "Arbol Tecnologico",
		"FMT_RESEARCHING": "%s — %d%%",
		"NOTIF_STORAGE_FULL": "Almacen lleno: se perdieron %d de %s!",
		"NOTIF_STORAGE_TRIMMED": "El almacen ya no da para tanto: se perdieron %d unidades (tope %d).",
		"LBL_STORAGE_USED": "Almacen",
		"NOTIF_RESEARCH_STARTED": "Investigando: %s",
		"NOTIF_RESEARCH_DONE": "Investigacion completa: %s",
		"TECH_BRANCH_INDUSTRIAL": "Industrial",
		"TECH_BRANCH_MILITARY": "Militar",
		"TECH_BRANCH_LOGISTICS": "Logistica",
		"TECH_IND_1": "Eficiencia Basica",
		"TECH_IND_2": "Almacenes Ampliados",
		"TECH_IND_3": "Produccion Avanzada",
		"TECH_IND_4": "Racionamiento",
		"TECH_IND_5": "Automatizacion",
		"TECH_MIL_1": "Disciplina",
		"TECH_MIL_2": "Entrenamiento",
		"TECH_MIL_3": "Tacticas Avanzadas",
		"TECH_MIL_4": "Fortificacion",
		"TECH_MIL_5": "Supremacia Militar",
		"TECH_LOG_1": "Rutas Comerciales",
		"TECH_LOG_2": "Red de Depositos",
		"TECH_LOG_3": "Construccion Rapida",
		"TECH_LOG_4": "Monopolio Comercial",
		"TECH_LOG_5": "Imperio Logistico",
		"LBL_PRODUCTION": "produccion",
		"LBL_STORAGE": "almacenamiento",
		"LBL_MORALE_WORD": "moral",

		# Construction Categories
		"LBL_CAT_ALL": "Todos",
		"LBL_CAT_PRODUCTION": "Produccion",
		"LBL_CAT_SUPPORT": "Soporte",
		"LBL_CAT_MILITARY": "Militar",
		"LBL_CAT_DECORATION": "Decoracion",
		"LBL_SEARCH": "Buscar...",
		"LBL_SELECT_BUILDING": "Selecciona un edificio",

		# Phase notifications (shown when a phase unlocks)
		"PHASE_1": "Tu asentamiento crece. La poblacion ahora consume recursos.",
		"PHASE_2": "El Mercado Imperial esta disponible. La moral ahora sube y baja.",
		"PHASE_3": "Eventos aleatorios comienzan. Las decoraciones ahora mejoran la moral.",
		"PHASE_4": "La era industrial ha llegado. Todos los sistemas activos.",

		# Objective hints (shown at top-center)
		"OBJ_PHASE_0": "Construye un Aserradero para empezar a producir madera.",
		"OBJ_PHASE_1": "Bien! Ahora construye una Mina de Oro para generar ingresos.",
		"OBJ_PHASE_1_DONE": "Construye un Deposito para almacenar mas recursos.",
		"OBJ_PHASE_2": "Construye un Deposito. El Mercado ya esta disponible para comerciar.",
		"OBJ_PHASE_2_DONE": "Construye una Fundicion para avanzar a la Era Industrial.",
		"OBJ_PHASE_3": "Construye una Fundicion para desbloquear el acero.",
		"OBJ_PHASE_3_DONE": "Sigue expandiendo tu imperio. Objetivo: Cuartel General Nv.3",
		"OBJ_PHASE_4": "Avanza hacia la Victoria Imperial. Construye el Cuartel General y mejoralo.",

		# Cloud Save
		"NOTIF_CLOUD_NOT_CONFIGURED": "Supabase no configurado. Usa guardado local.",
		"NOTIF_CLOUD_AUTH_FAILED": "Error de autenticacion en la nube.",
		"NOTIF_CLOUD_CONNECTED": "Conectado a la nube.",
		"NOTIF_CLOUD_SAVED": "Guardado en la nube.",
		"NOTIF_CLOUD_LOAD_FAILED": "Error al cargar desde la nube.",
		"NOTIF_CLOUD_NO_SAVE": "No hay guardado en la nube.",
		"NOTIF_CLOUD_LOADED": "Cargado desde la nube.",

		# Objective Panel
		"LBL_OBJ_TITLE": "¿QUE HACER? - OBJETIVOS",
		"LBL_OBJ_MISSION": "TU MISION",
		"LBL_OBJ_MISSION_DESC": "Transforma un asentamiento remoto en una Potencia Industrial Monumental. Debes gestionar recursos, energia y poblacion para expandir tu base.",
		"LBL_OBJ_STEPS": "PASOS INICIALES",
		"LBL_OBJ_STEP_1": "1. ENERGIA: Construye un NUCLEO para dar energia a tus edificios.",
		"LBL_OBJ_STEP_2": "2. EXTRACCION: Construye SERRERIAS y MINAS para obtener recursos basicos.",
		"LBL_OBJ_STEP_3": "3. POBLACION: Construye CASAS. Sin gente, las fabricas no funcionan.",
		"LBL_OBJ_STEP_4": "4. LOGISTICA: Conecta edificios con ALMACENES para guardar tu produccion.",
		"LBL_OBJ_STEP_5": "5. PROGRESO: Usa el Arbol Tecnologico para desbloquear edificios avanzados.",
		"LBL_OBJ_TIP": "TIP: Usa el menu de construccion (abajo a la derecha) para empezar.",
		"BTN_UNDERSTOOD": "ENTENDIDO!",
		"BTN_OBJECTIVES": "¿QUE HACER?",

		# Settings Panel
		"BTN_SETTINGS": "AJUSTES",
		"LBL_SETTINGS_TITLE": "AJUSTES",
		"LBL_SETTINGS_AUDIO": "AUDIO",
		"LBL_VOL_MASTER": "Volumen general",
		"LBL_VOL_MUSIC": "Musica",
		"LBL_VOL_SFX": "Efectos de sonido",
		"LBL_SETTINGS_UI": "INTERFAZ",
		"LBL_SHOW_GRID": "Mostrar cuadricula del mapa",
		"LBL_FULLSCREEN": "Pantalla completa (F11)",

		# Helper
		"BTN_HELPER_TIP": "Ayudante: muestra u oculta las guias en pantalla",
		"BTN_BUILDING_GUIDE": "GUIA DE EDIFICIOS",
		"LBL_GUIDE_TITLE": "GUIA DE EDIFICIOS",
		"LBL_GUIDE_COST": "Costo",
		"LBL_GUIDE_WORKERS": "Trabajadores",
		"LBL_GUIDE_PRODUCES": "Produce",
		"LBL_GUIDE_HOUSING": "Alojamiento",
		"LBL_GUIDE_MORALE": "Moral",
		"LBL_HELP_RESOURCES": "Tus recursos: oro y madera (luego acero y petroleo). El /800 es tu capacidad de almacenamiento.",
		"LBL_HELP_MENUS": "El boton ☰ abre los menus: Que Hacer, Progreso, Mercado, Tecnologia, Ejercito, Ajustes y CONSTRUIR.",
		"LBL_HELP_OBJECTIVE": "Aqui aparece tu objetivo actual.",
		"LBL_HELP_BUILD": "Para construir: abre ☰, pulsa CONSTRUIR (abajo), elige un edificio y toca una celda libre del mapa.",
		"LBL_HELP_CAMERA": "Mueve la camara con estas flechas o con WASD.",
		"LBL_HELP_ZOOM": "Rota la camara y haz zoom (tambien con la rueda del raton).",

		# Army / Units
		"BTN_ARMY": "EJERCITO",
		"LBL_ARMY_TITLE": "CUARTEL - EJERCITO",
		"UNIT_INFANTRY": "Infanteria",
		"UNIT_ARTILLERY": "Artilleria",
		"UNIT_VEHICLE": "Vehiculo Blindado",
		"LBL_MILITARY_POWER": "Poder Militar: %d",
		"LBL_ARMY_CAPACITY": "Capacidad: %d / %d",
		"LBL_ARMY_SLOTS": "Entrenamiento: %d / %d ranuras",
		"LBL_ARMY_OWNED": "Tienes: %d",
		"LBL_ARMY_TIER": "Nivel %d",
		"LBL_ARMY_POWER_EACH": "Poder %d",
		"LBL_ARMY_UPKEEP": "Mantenimiento %d oro",
		"LBL_ARMY_IN_TRAINING": "En entrenamiento",
		"BTN_TRAIN": "ENTRENAR",
		"LBL_ARMY_NO_UNIT": "Unidad desconocida",
		"LBL_ARMY_NEED_BARRACKS": "Necesitas un Cuartel",
		"LBL_ARMY_LOCKED": "Bloqueada (era superior)",
		"LBL_ARMY_SLOTS_FULL": "Ranuras de entrenamiento llenas",
		"LBL_ARMY_AT_CAP": "Ejercito al maximo",
		"LBL_ARMY_EMPTY": "Aun no tienes tropas. Entrena unidades en el Cuartel.",
		"NOTIF_UPKEEP_UNPAID": "Sin oro para el ejercito: faltan %d oro",

		# Cancelacion (Tasa de Corrupcion), hambruna y desercion
		"FMT_CANCEL_REFUND": "Cancelar — devuelve %s",
		"LBL_CANCEL_NO_REFUND": "Cancelar — sin reembolso",
		"LBL_CANCEL_RATE": "Tasa de Corrupcion: vuelve el %d%%",
		"LBL_CANCEL_RATE_STORM": "Con la Tormenta en marcha solo vuelve el %d%%",
		"FMT_DEMOLISH_IN_PROGRESS": "Hay algo en curso: devuelve %s",
		"NOTIF_STARVATION": "Hambruna: muere %d habitante por falta de suministros.",
		"NOTIF_DESERTION": "Desercion: %d %s abandonan el ejercito sin cobrar.",

		# Combat / Expeditions
		"BTN_SKIRMISH": "ESCARAMUZAS",
		"BTN_LAUNCH_EXPEDITION": "LANZAR EXPEDICION",
		"BTN_ABANDON": "Abandonar",
		"BTN_END_TURN": "Terminar turno",
		"BTN_DEFEND": "Defender",
		"BTN_WAIT": "Esperar",
		"BTN_DEV_SKIRMISH": "Escaramuza de prueba",
		"LBL_SKIRMISH_TITLE": "ESCARAMUZAS - EXPEDICION",
		"LBL_DEPLOY_CAP": "Comprometidas: %d / %d",
		"LBL_EXPEDITION_MAP": "Mapa de expedicion",
		"LBL_ENCOUNTER_N": "Encuentro %d",
		"LBL_BOSS": "JEFE",
		"LBL_TURN_PLAYER": "Tu turno",
		"LBL_TURN_ENEMY": "Turno enemigo",
		"LBL_ROUND": "Ronda %d / %d",
		"LBL_DRAFT_TITLE": "Elige una mejora",
		"LBL_VICTORY": "VICTORIA",
		"LBL_DEFEAT": "DERROTA",
		"LBL_REWARDS": "Botin",
		"LBL_CASUALTIES": "Bajas",
		"LBL_NO_CASUALTIES": "Sin bajas",
		# La Tormenta Imperial
		"BTN_REPAIR": "REPARAR",
		"LBL_DAMAGED": "Danado: %d%% de integridad",
		"LBL_RUINED": "EN RUINAS - no produce nada",
		"MSG_REPAIR_NOT_NEEDED": "No necesita reparacion",
		"MSG_REPAIR_NO_RESOURCES": "Faltan recursos para repararlo",
		"NOTIF_BUILDING_RUINED": "%s ha quedado en ruinas.",
		"STORM_INCOMING_FIRST": "El aire viene sucio del este.",
		"STORM_INCOMING": "Otra vez el aire del este.",
		"STORM_FALSE_ALARM": "El aire se limpia. Esta vez no bajaron.",
		"STORM_ASH_STARTED": "Empieza a caer ceniza.",
		"STORM_STARTED": "La tormenta rompe sobre la isla.",
		"STORM_ENDED": "El aire aclara.",
		"STORM_TITHE_PAID": "Los Tasadores han cobrado el Diezmo.",
		"STORM_TITHE_UNDEFENDED": "Nadie en pie. Los Tasadores cobran sin bajarse del carro.",
		"STORM_TITHE_DEFENDING": "LOS TASADORES EXIGEN EL DIEZMO",
		"STORM_TITHE_REPELLED": "Los Tasadores se retiran sin cobrar.",
		"STORM_TITHE_TOWER_CREWS": "Las torres encienden los reflectores y arman sus posiciones (+%d en la linea).",
		"STORM_PHASE_WARNING": "ADVERTENCIA",
		"STORM_PHASE_ASH": "CENIZA",
		"STORM_PHASE_STORM": "TORMENTA",
		"STORM_PHASE_TITHE": "DIEZMO",
		"STORM_TITHE_SEIZED": "No habia con que pagar. Los Tasadores embargan %d bienes.",
		"STORM_TITHE_CONSCRIPTED": "La cuenta no cuadraba. Se llevan %d de los nuestros.",
		"STORM_ASH_QUEUE_WARNING": "La ceniza avisa: %d en la cola. Si rompe la Tormenta se pierden con su coste (%s).",
		"STORM_ASH_QUEUE_WARNING_FREE": "La ceniza avisa: %d minando. Si rompe la Tormenta, el trabajo hecho no se recupera.",
		"STORM_ASH_TRAINING_WARNING": "La ceniza avisa: %d en el cuartel. Si rompe la Tormenta se pierden con su coste (%s).",
		"NOTIF_STORM_ATE_PROCESS": "La tormenta se llevo %s. Perdido su coste: %s.",
		"NOTIF_STORM_ATE_MINING": "La tormenta enterro %s. El trabajo hecho no vuelve.",
		"NOTIF_STORM_ATE_TRAINING": "La tormenta se llevo a %s a medio entrenar. Perdido su coste: %s.",
		# La Auditoria Final
		"AUDIT_TITLE": "LA AUDITORIA FINAL",
		"AUDIT_SUMMONED": "El Cuartel General esta terminado. La Regencia baja a auditarlo.",
		"AUDIT_SUMMONED_DESC": "Vienen %d oleadas. Pelea la guarnicion que este en casa.",
		"AUDIT_STARTED": "La auditoria empieza. Ya no se reentrena a nadie.",
		"AUDIT_WAVE": "Oleada %d de %d",
		"AUDIT_WAVE_CLEARED": "Oleada rechazada. Quedan %d.",
		"AUDIT_LAST_WAVE": "Ultima oleada. Baja todo lo que les queda.",
		"AUDIT_ATTRITION": "Lo que cae, cae. No hay relevos.",
		"AUDIT_LOST": "La auditoria pasa por encima. Cobran el Diezmo maximo y se van.",
		"AUDIT_LOST_DESC": "No se pierde la partida. Rehaz el ejercito y vuelve a convocarlos.",
		"AUDIT_RESUMMON_LOCKED": "Hacen falta %d unidades en pie para volver a convocarlos.",
		"AUDIT_WON_TITLE": "VICTORIA IMPERIAL",
		"AUDIT_WON_BODY": "La Tormenta se detiene. Para siempre.",
		"AUDIT_WON_MEANING": "No has roto el sistema. Te has quedado con el.",
		"AUDIT_WON_LAST_LINE": "El Diezmo se cobrara el martes.",
		"BTN_AUDIT_BEGIN": "QUE BAJEN",
		"BTN_AUDIT_RESUMMON": "VOLVER A CONVOCARLOS",
		"LBL_MORALE_DELTA": "Moral %+d",
		"LBL_RISK_LOW": "Riesgo bajo",
		"LBL_RISK_MED": "Riesgo medio",
		"LBL_RISK_HIGH": "Riesgo alto",
		"LBL_MORALE_COMBAT": "Moral %d: iniciativa %+d, ataque x%.2f",
		"LBL_UNIT_IN_EXPEDITION": "En campana",
		"MSG_NO_UNITS": "No tienes unidades disponibles para una expedicion.",
		"MSG_EXPEDITION_WON": "Expedicion completada. Botin: %s",
		"MSG_EXPEDITION_LOST": "Expedicion aniquilada. Bajas: %d",
		"MSG_EXPEDITION_ABANDONED": "Expedicion abandonada. Conservas el botin.",
		"MSG_CONFIRM_ABANDON": "Abandonaras la expedicion. Conservas el botin y las supervivientes.",
		"OBJ_ELIMINATE_ALL": "Elimina a todas las unidades enemigas",
		"DRAFT_ATK": "Doctrina de asalto: +%d ataque",
		"DRAFT_DEF": "Blindaje improvisado: +%d defensa",
		"DRAFT_HP_HEAL": "Puesto de campana: cura %d%% de vida",
		"DRAFT_MOVE": "Orugas reforzadas: +%d movimiento",
		"DRAFT_INIT": "Ordenes anticipadas: +%d iniciativa",

		# Building Info extras
		"LBL_POP_CAPACITY": "+%d poblacion",
		"LBL_MORALE_BONUS": "+%d moral",
		"LBL_ROTATE_BUILDING": "Rotar edificio (R)",

		# Tech bonuses
		"FMT_SPREAD_REDUCTION": "-%d%% margen",
		"FMT_CONSUMPTION_REDUCTION": "-%d%% consumo",
		"FMT_BUILD_SPEED": "+%d%% velocidad",

		# Tutorial
		# La intro condensa 03_LORE.md pagina a pagina: frases cortas, sin
		# suavizar. Las tarjetas de "como se juega" salen de docs/14-guia-de-juego.md.
		"BTN_TUTORIAL_NEXT": "Siguiente",
		"BTN_TUTORIAL_SKIP": "Saltar",
		"BTN_TUTORIAL_START": "Empezar",
		"BTN_TUTORIAL_OK": "Entendido",
		"LBL_TUTORIAL_PAGE": "%d / %d",
		"LBL_TUTORIAL_SECTION_LORE": "EL MUNDO",
		"LBL_TUTORIAL_SECTION_PLAY": "COMO SE JUEGA",
		"TUT_INTRO_1_TITLE": "El Imperio Sin Ocaso",
		"TUT_INTRO_1_BODY": "Asi se llama a si mismo: el Imperio Sin Ocaso, aquel sobre el que el sol jamas se pone.\n\nEs cierto. Sobre ellos no se pone nunca.\n\nSobre nosotros no sale desde hace tres generaciones. Vivimos bajo un techo de ceniza que ellos fabrican y despachan, en una penumbra permanente de color oxido. Han repartido la luz del mundo y se han quedado con toda.\n\nSu lema: \"Donde alcanza la luz\". Lo que significa de verdad: hasta donde ellos deciden que llegue.",
		"TUT_INTRO_2_TITLE": "El Perpetuo",
		"TUT_INTRO_2_BODY": "El Imperio lo gobierna el Perpetuo, emperador por derecho eterno.\n\nNadie lo ha visto en ciento catorce inviernos. No hay retratos nuevos. No hay discursos. Hay firmas: miles y miles, todas identicas, en cada orden de tributo, cada sentencia y cada despacho de tormenta.\n\nEl Perpetuo esta muerto y lleva muerto un siglo.\n\nNo lo ocultan por devocion. Lo ocultan por aritmetica: anunciar una muerte abre una sucesion, una sucesion es una guerra, y una guerra interrumpe el cobro. Un emperador muerto no cambia de opinion y no perdona deudas. Es el gobernante perfecto. Por eso lo conservan.",
		"TUT_INTRO_3_TITLE": "La Regencia",
		"TUT_INTRO_3_BODY": "Si el emperador no gobierna, alguien gobierna.\n\nLa Regencia se fundo como medida temporal para administrar el Imperio en ausencia del Perpetuo. Eso fue hace ciento catorce inviernos. Sigue siendo temporal.\n\nNo es un ejercito ni una corte: es una contaduria. Funcionarios vitalicios que no conquistan territorios, los dan de alta. Que no declaran guerras, suspenden suministros. Que saben exactamente cuanto grano hay en cada provincia y cuanto aguanta cada provincia sin el.\n\nSu lema: \"Nada se pierde\". Suena a consuelo. Es un inventario.",
		"TUT_INTRO_4_TITLE": "La Tormenta no es clima",
		"TUT_INTRO_4_BODY": "La gente cree que la Tormenta es clima. Un castigo del mundo, mala suerte de haber nacido a sotavento. Se le reza. Se la aguanta.\n\nLa Tormenta no es clima. Es correo.\n\nAl otro lado del oceano estan las Chimeneas: una cordillera artificial cuyo unico proposito es empujar el aire. Toda la escoria del Imperio se carga en el viento y se despacha. Y sale en fecha.\n\nNo la mandan para ensuciarnos. La mandan para ablandarnos. Con la ceniza llegan los Tasadores: peritos armados que miran tus almacenes, anotan y se llevan su parte. A eso lo llaman el Diezmo. Primero la ruina, despues la cuenta. Siempre en ese orden.",
		"TUT_INTRO_5_TITLE": "Nosotros: los Amortizados",
		"TUT_INTRO_5_BODY": "No nos derrotaron. Nos dieron de baja.\n\nHace tres generaciones, un funcionario que no conocemos hizo un calculo que no vimos y decidio que esta isla habia dejado de ser rentable. Figuramos en el libro como perdida asumida. Nos dejaron de contar. Y sobrevivimos.\n\nLo que no esta en el libro no se cobra. Esa invisibilidad fue lo unico bueno que nos paso.\n\nPero hemos crecido. Se ven chimeneas desde el mar. Y la Regencia, que no perdona un error de calculo, ha vuelto a abrir la pagina.\n\nCrecer es lo que te hace visible. Ser visible es lo que trae la Tormenta.",
		"TUT_INTRO_6_TITLE": "Sobre el barro de la historia",
		"TUT_INTRO_6_BODY": "\"Sobre el barro de la historia, levantaremos monumentos de acero.\"\n\nEsto es lo que tienes: un Nucleo, trescientos de oro, doscientos de madera y una isla que el Imperio tacho.\n\nConstruye. Crece. Y cuando el aire venga sucio del este, que te encuentre preparado.\n\nA continuacion, como se juega.",
		"TUT_PLAY_1_TITLE": "El Nucleo y las primeras obras",
		"TUT_PLAY_1_BODY": "El Nucleo es tu centro. No se puede demoler y nunca cae.\n\nLo primero, siempre: un aserradero. Sin madera no hay nada, y todo lo que sigue la cuesta. Colocalo pegado a un bosque: los extractores van junto a su yacimiento, igual que la mina de oro junto a una veta.\n\nDespues, una casa. Casi todo edificio necesita gente que lo atienda; sin trabajadores se queda parado.\n\nBoton CONSTRUIR abajo. WASD o arrastrar para mover la camara, rueda para el zoom, R para rotar antes de colocar.",
		"TUT_PLAY_2_TITLE": "Una sola bolsa",
		"TUT_PLAY_2_BODY": "Tus cuatro recursos (oro, madera, acero y petroleo) comparten UNA sola bolsa de almacenamiento. Si esta llena, lo que produzcas se pierde. Gasta, o construye almacenes.\n\nTu gente come: cada persona consume 1 madera y 1 oro por ciclo. Si no puedes pagarlo, la moral se desploma.\n\nLa moral multiplica tu produccion: a 0 produces la mitad, a 100 un 20% mas. Cuando crezcas, crece primero la madera.",
		"TUT_PLAY_3_TITLE": "La Tormenta se ve venir",
		"TUT_PLAY_3_BODY": "La Tormenta no cae de golpe. Tiene fases, y el indicador del cielo te las dice:\n\nAVISO: hay ceniza en el horizonte. Todavia no cae nada.\nCENIZA: la produccion baja, y lo que este en cola se perdera.\nTORMENTA: rompe edificios.\nDIEZMO: llegan los Tasadores a cobrar.\n\nGasta antes lo que no quieras que se lleven. Repara despues lo que rompa. Y ten guarnicion: si los Tasadores encuentran resistencia, se pelea en el tablero, y si ganas no se llevan nada.",
		"TUT_PLAY_4_TITLE": "Torres y guarnicion",
		"TUT_PLAY_4_BODY": "Las torres en pie mitigan el dano de la Tormenta, y su dotacion pelea cuando llegan los Tasadores.\n\nEl Cuartel entrena unidades: infanteria, artilleria y vehiculos. Cada cuartel entrena una a la vez, y todas cobran sueldo en oro.\n\nEn el tablero: una unidad se mueve y luego ataca. La artilleria no dispara a un enemigo pegado a ella. Defender duplica la defensa hasta tu siguiente turno.\n\nEl camino: aserradero, casas, mina, fundicion (era 2), cuartel, refineria sobre un pozo (era 3), torres, Cuartel General. A nivel 3 convoca la auditoria final de la Regencia. Sobrevivela.",
		"TUT_TIP_INCOMING_TITLE": "Aviso: ceniza en el horizonte",
		"TUT_TIP_INCOMING_BODY": "El aire viene sucio del este. Todavia no cae nada, pero caera.\n\nAhora: gasta lo que no quieras que se lleven, repara lo que este tocado y asegurate de tener guarnicion. Los Tasadores cobran sobre lo que encuentran en tus almacenes.",
		"TUT_TIP_ASH_TITLE": "Cae ceniza",
		"TUT_TIP_ASH_BODY": "La produccion baja mientras dure. Y ojo: los procesos en marcha y las unidades en entrenamiento se perderan cuando caiga la Tormenta. Termina lo que puedas y no empieces nada nuevo.",
		"TUT_TIP_STORM_TITLE": "Tormenta",
		"TUT_TIP_STORM_BODY": "Ahora rompe edificios. Las torres en pie mitigan el dano. Un edificio que llega a cero queda en ruinas y deja de producir hasta que lo repares. Aguanta: pasa.",
		"TUT_TIP_TITHE_TITLE": "Los Tasadores",
		"TUT_TIP_TITHE_BODY": "Han venido a cobrar el Diezmo. Tu guarnicion pelea en el tablero. Si ganas, no se llevan nada. Si pierdes, o no tienes con que pelear, se llevan un porcentaje de tu almacen.",
		"TUT_TIP_RUINED_TITLE": "Un edificio en ruinas",
		"TUT_TIP_RUINED_BODY": "En ruinas no produce. Sigue en su sitio: haz clic en el edificio y pulsa REPARAR. Cuesta recursos, pero menos que volver a construirlo.",
		"TUT_TIP_OVERFLOW_TITLE": "La bolsa esta llena",
		"TUT_TIP_OVERFLOW_BODY": "Tus cuatro recursos comparten una sola bolsa, y lo que no cabe se pierde. Gasta en edificios o construye un almacen: cada uno amplia el tope en 500.",
		"TUT_TIP_BOARD_TITLE": "El tablero",
		"TUT_TIP_BOARD_BODY": "Por turnos, en orden de iniciativa. Una unidad puede moverse y luego atacar; atacar termina su turno. La artilleria no dispara a un enemigo pegado a ella. Defender duplica la defensa hasta tu siguiente turno.",
	},
	"en": {
		"BTN_BUILD": "BUILD",
		"BTN_CLOSE": "Close",
		"BTN_MOVE": "Move",
		"BTN_DEMOLISH": "Demolish",
		"BTN_RENAME": "Rename",
		"BTN_CLEAR": "CLEAR",
		"BTN_UPGRADE": "Upgrade",
		"BTN_CONFIRM": "Confirm",
		"BTN_CANCEL": "Cancel",
		"CONFIRM_NEW_GAME": "This will erase your current game and start over. It cannot be undone.",
		"LBL_SETTINGS_GAME": "GAME",

		"LBL_ACTIONS": "Actions",
		"LBL_NO_ACTIONS": "No actions available",
		"LBL_BUILDINGS_AVAILABLE": "Available buildings",
		"LBL_BUILDING_NAME_PLACEHOLDER": "Building name...",
		"LBL_FREE": "Free",
		"LBL_NATURAL_RESOURCE": "Natural resource available for extraction.",
		"LBL_LEVEL": "Level %d",
		"LBL_MAX_LEVEL": "Max level",
		"LBL_UPGRADE_TO": "Upgrade to Level %d",
		"LBL_STORAGE_CAP": "Storage: %d/%d",
		"LBL_LIMIT_REACHED": "Limit reached (%d/%d)",
		"LBL_REQUIRES": "Requires: %s",
		"LBL_REQUIRES_DEPOSIT": "Must be placed on an oil deposit",
		"LBL_NEEDS_FOREST_NEAR": "The sawmill needs a forest next to it",
		"LBL_NEEDS_GOLD_VEIN_NEAR": "The gold mine needs a gold vein next to it",
		"LBL_NEEDS_IRON_NEAR": "The foundry needs an iron deposit next to it",
		"LBL_STATUS_IDLE": "Zzz",
		"LBL_NOT_ENOUGH_RESOURCES": "Not enough resources!",
		"LBL_UPGRADE_COMPLETE": "Upgrade complete!",

		"FMT_COST": "Cost: %s",
		"FMT_PRODUCES": "Produces: %s",
		"FMT_PRODUCES_EVERY": "Produces: %s every %ds",
		"FMT_PROGRESS": "%s — %ds remaining",
		"FMT_CONSTRUCTION": "Building: %d%% — %ds remaining",
		"FMT_CONSTRUCTING": "Building %d%%",
		"FMT_UPGRADING": "Upgrading %d%%",
		"FMT_CONSTRUCTION_COMPLETE": "Construction complete!",
		"FMT_DURATION": "Duration: %ds",
		"FMT_OFFLINE_TITLE": "While you were away (%s)",
		"FMT_DEMOLISH_CONFIRM": "Demolish %s?\nRefund: %d%%",
		"LBL_DEPOSIT_USES": "%d uses remaining",
		"LBL_DEPOSIT_DEPLETED": "Deposit depleted!",

		"DEP_GOLD_VEIN": "Gold Vein",
		"DEP_IRON": "Iron",
		"DEP_OIL": "Oil Well",
		"DEP_FOREST": "Forest",

		"PROC_WOOD_PLANKS": "Wood Planks",
		"PROC_IRON_SHEETS": "Iron Sheets",
		"PROC_WATER_PIPES": "Water Pipes",
		"PROC_REFINED_LUMBER": "Refined Lumber",
		"PROC_CHARCOAL": "Charcoal",
		"PROC_DEEP_MINING": "Deep Mining",
		"PROC_GEM_EXTRACTION": "Gem Extraction",
		"PROC_ALLOY_SMELTING": "Alloy Smelting",
		"PROC_ARMOR_PLATES": "Armor Plates",
		"PROC_FUEL_DISTILLATION": "Fuel Distillation",
		"PROC_CHEMICAL_PROCESSING": "Chemical Processing",
		"PROC_MINE_GOLD": "Mine Gold",
		"PROC_MINE_IRON": "Mine Iron",
		"PROC_MINE_OIL": "Extract Oil",
		"PROC_MINE_WOOD": "Chop Trees",

		# Market
		"BTN_MARKET": "MARKET",
		"BTN_BUY": "Buy",
		"BTN_SELL": "Sell",
		"LBL_MARKET_TITLE": "Imperial Market",
		"LBL_RESOURCE": "Resource",
		"LBL_BUY_PRICE": "Buy",
		"LBL_SELL_PRICE": "Sell",
		"LBL_AMOUNT": "Qty.",
		"LBL_YOUR_GOLD": "Your gold: %d",

		# Progression
		"BTN_PROGRESS": "PROGRESS",
		"LBL_PROGRESS_TITLE": "Imperial Progress",
		"LBL_CURRENT_ERA": "Current era",

		# Eras
		"ERA_FRONTIER": "Frontier",
		"ERA_INDUSTRIAL": "Industrial",
		"ERA_PETROLEUM": "Petroleum",

		# Milestones
		"MILE_PIONEER": "Pioneer — Build Sawmill",
		"MILE_PROSPECTOR": "Prospector — Build Gold Mine",
		"MILE_STOCKPILER": "Stockpiler — Build Warehouse",
		"MILE_INDUSTRIALIST": "Industrialist — Build Foundry",
		"MILE_OIL_BARON": "Oil Baron — Build Refinery",
		"MILE_MERCHANT": "Merchant — 10 trades",
		"MILE_COMMANDER": "Commander — Barracks + 2 Towers",
		"MILE_GENERAL": "General — Build Headquarters",
		"MILE_VICTORY": "Imperial Victory — Headquarters Lv.3",
		"FMT_MILESTONE_COMPLETE": "Milestone complete: %s",
		"FMT_ERA_UNLOCKED": "New era: %s",

		# Victory
		"LBL_VICTORY_TITLE": "IMPERIAL VICTORY",
		"LBL_VICTORY_SUBTITLE": "Your dieselpunk empire has reached the pinnacle of power. The storm is yours.",
		"LBL_STAT_TIME": "Time played:",
		"LBL_STAT_BUILDINGS": "Buildings built:",
		"LBL_STAT_TRADES": "Trades:",
		"LBL_STAT_MILESTONES": "Milestones completed:",
		"BTN_CONTINUE": "Keep playing",
		"BTN_NEW_GAME": "New game",

		# Locked resources
		"LBL_LOCKED_RESOURCE": "Resource locked",
		"LBL_DEPOSIT_LOCKED": "Resource not yet unlocked. Advance your era to access.",

		# Population & Workers
		"LBL_POPULATION": "Population: %d/%d",
		"LBL_WORKERS": "Workers: %d/%d",
		"LBL_MORALE": "Morale: %d%%",
		"LBL_WORKERS_NEEDED": "Requires %d workers",
		"LBL_NO_WORKERS": "No workers available",
		"LBL_NO_WORKERS_SHORT": "NO WORKERS",
		"NOTIF_POP_GREW": "Population grew: %d/%d",
		"NOTIF_NO_WOOD": "Not enough wood for the population!",
		"NOTIF_NO_GOLD": "Not enough gold to pay wages!",
		"NOTIF_LOW_MORALE": "Morale is very low! Production reduced.",
		"NOTIF_BUILT": "%s built!",
		"NOTIF_UPGRADE_DONE": "%s upgraded to Lv.%d!",
		"NOTIF_DEPOSIT_GONE": "%s depleted.",

		# Notifications / Log
		"BTN_LOG": "LOG",
		"LBL_LOG_TITLE": "Activity Log",

		# Random Events
		"EVENT_STORM": "Storm",
		"EVENT_STORM_DESC": "Strong winds damage wood reserves.",
		"EVENT_RESOURCE_FIND": "Resource Find",
		"EVENT_RESOURCE_FIND_DESC": "Scouts discover abandoned resources.",
		"EVENT_MINING_ACCIDENT": "Mining Accident",
		"EVENT_MINING_ACCIDENT_DESC": "A cave-in at the mine. You lose a worker.",
		"EVENT_TRADE_CARAVAN": "Trade Caravan",
		"EVENT_TRADE_CARAVAN_DESC": "A caravan passes through and leaves gold.",
		"EVENT_FESTIVAL": "Festival",
		"EVENT_FESTIVAL_DESC": "The people celebrate. Big morale boost.",
		"EVENT_PLAGUE": "Plague",
		"EVENT_PLAGUE_DESC": "Disease spreads. Morale drops drastically.",
		"EVENT_PLAGUE_OVER": "The plague has passed.",
		"EVENT_GOOD_HARVEST": "Good Harvest",
		"EVENT_GOOD_HARVEST_DESC": "Nearby forests yield extra wood.",
		"EVENT_BANDIT_RAID": "Bandit Raid",
		"EVENT_BANDIT_RAID_DESC": "Bandits loot some of your gold.",

		# Tech Tree
		"BTN_TECH": "TECH",
		"LBL_TECH_TITLE": "Tech Tree",
		"FMT_RESEARCHING": "%s — %d%%",
		"NOTIF_STORAGE_FULL": "Storage full: %d %s lost!",
		"NOTIF_STORAGE_TRIMMED": "Storage no longer holds that much: %d units lost (cap %d).",
		"LBL_STORAGE_USED": "Storage",
		"NOTIF_RESEARCH_STARTED": "Researching: %s",
		"NOTIF_RESEARCH_DONE": "Research complete: %s",
		"TECH_BRANCH_INDUSTRIAL": "Industrial",
		"TECH_BRANCH_MILITARY": "Military",
		"TECH_BRANCH_LOGISTICS": "Logistics",
		"TECH_IND_1": "Basic Efficiency",
		"TECH_IND_2": "Expanded Storage",
		"TECH_IND_3": "Advanced Production",
		"TECH_IND_4": "Rationing",
		"TECH_IND_5": "Automation",
		"TECH_MIL_1": "Discipline",
		"TECH_MIL_2": "Training",
		"TECH_MIL_3": "Advanced Tactics",
		"TECH_MIL_4": "Fortification",
		"TECH_MIL_5": "Military Supremacy",
		"TECH_LOG_1": "Trade Routes",
		"TECH_LOG_2": "Depot Network",
		"TECH_LOG_3": "Rapid Construction",
		"TECH_LOG_4": "Trade Monopoly",
		"TECH_LOG_5": "Logistics Empire",
		"LBL_PRODUCTION": "production",
		"LBL_STORAGE": "storage",
		"LBL_MORALE_WORD": "morale",

		# Construction Categories
		"LBL_CAT_ALL": "All",
		"LBL_CAT_PRODUCTION": "Production",
		"LBL_CAT_SUPPORT": "Support",
		"LBL_CAT_MILITARY": "Military",
		"LBL_CAT_DECORATION": "Decoration",
		"LBL_SEARCH": "Search...",
		"LBL_SELECT_BUILDING": "Select a building",

		# Phase notifications
		"PHASE_1": "Your settlement grows. Population now consumes resources.",
		"PHASE_2": "The Imperial Market is open. Morale now rises and falls.",
		"PHASE_3": "Random events begin. Decorations now improve morale.",
		"PHASE_4": "The industrial era has arrived. All systems active.",

		# Objective hints
		"OBJ_PHASE_0": "Build a Sawmill to start producing wood.",
		"OBJ_PHASE_1": "Good! Now build a Gold Mine to generate income.",
		"OBJ_PHASE_1_DONE": "Build a Warehouse to store more resources.",
		"OBJ_PHASE_2": "Build a Warehouse. The Market is now open for trade.",
		"OBJ_PHASE_2_DONE": "Build a Foundry to advance to the Industrial Era.",
		"OBJ_PHASE_3": "Build a Foundry to unlock steel.",
		"OBJ_PHASE_3_DONE": "Keep expanding. Goal: Headquarters Level 3.",
		"OBJ_PHASE_4": "Push for Imperial Victory. Build and upgrade Headquarters.",

		# Cloud Save
		"NOTIF_CLOUD_NOT_CONFIGURED": "Supabase not configured. Using local save.",
		"NOTIF_CLOUD_AUTH_FAILED": "Cloud authentication failed.",
		"NOTIF_CLOUD_CONNECTED": "Connected to cloud.",
		"NOTIF_CLOUD_SAVED": "Saved to cloud.",
		"NOTIF_CLOUD_LOAD_FAILED": "Failed to load from cloud.",
		"NOTIF_CLOUD_NO_SAVE": "No cloud save found.",
		"NOTIF_CLOUD_LOADED": "Loaded from cloud.",

		# Objective Panel
		"LBL_OBJ_TITLE": "WHAT TO DO? - OBJECTIVES",
		"LBL_OBJ_MISSION": "YOUR MISSION",
		"LBL_OBJ_MISSION_DESC": "Transform a remote settlement into a Monumental Industrial Power. Manage resources, energy, and population to expand your base.",
		"LBL_OBJ_STEPS": "INITIAL STEPS",
		"LBL_OBJ_STEP_1": "1. ENERGY: Build a CORE to power your buildings.",
		"LBL_OBJ_STEP_2": "2. EXTRACTION: Build SAWMILLS and MINES to obtain basic resources.",
		"LBL_OBJ_STEP_3": "3. POPULATION: Build HOUSES. Without people, factories don't work.",
		"LBL_OBJ_STEP_4": "4. LOGISTICS: Connect buildings with WAREHOUSES to store production.",
		"LBL_OBJ_STEP_5": "5. PROGRESS: Use the Tech Tree to unlock advanced buildings.",
		"LBL_OBJ_TIP": "TIP: Use the construction menu (bottom right) to get started.",
		"BTN_UNDERSTOOD": "GOT IT!",
		"BTN_OBJECTIVES": "WHAT TO DO?",

		# Settings Panel
		"BTN_SETTINGS": "SETTINGS",
		"LBL_SETTINGS_TITLE": "SETTINGS",
		"LBL_SETTINGS_AUDIO": "AUDIO",
		"LBL_VOL_MASTER": "Master volume",
		"LBL_VOL_MUSIC": "Music",
		"LBL_VOL_SFX": "Sound effects",
		"LBL_SETTINGS_UI": "INTERFACE",
		"LBL_SHOW_GRID": "Show map grid",
		"LBL_FULLSCREEN": "Fullscreen (F11)",

		# Helper
		"BTN_HELPER_TIP": "Helper: show or hide the on-screen guides",
		"BTN_BUILDING_GUIDE": "BUILDING GUIDE",
		"LBL_GUIDE_TITLE": "BUILDING GUIDE",
		"LBL_GUIDE_COST": "Cost",
		"LBL_GUIDE_WORKERS": "Workers",
		"LBL_GUIDE_PRODUCES": "Produces",
		"LBL_GUIDE_HOUSING": "Housing",
		"LBL_GUIDE_MORALE": "Morale",
		"LBL_HELP_RESOURCES": "Your resources: gold and wood (later steel and oil). The /800 is your storage capacity.",
		"LBL_HELP_MENUS": "The ☰ button opens the menus: What To Do, Progress, Market, Technology, Army, Settings and BUILD.",
		"LBL_HELP_OBJECTIVE": "Your current objective appears here.",
		"LBL_HELP_BUILD": "To build: open ☰, press BUILD (bottom), pick a building and tap a free map cell.",
		"LBL_HELP_CAMERA": "Move the camera with these arrows or WASD.",
		"LBL_HELP_ZOOM": "Rotate the camera and zoom (mouse wheel works too).",

		# Army / Units
		"BTN_ARMY": "ARMY",
		"LBL_ARMY_TITLE": "BARRACKS - ARMY",
		"UNIT_INFANTRY": "Infantry",
		"UNIT_ARTILLERY": "Artillery",
		"UNIT_VEHICLE": "Armored Vehicle",
		"LBL_MILITARY_POWER": "Military Power: %d",
		"LBL_ARMY_CAPACITY": "Capacity: %d / %d",
		"LBL_ARMY_SLOTS": "Training: %d / %d slots",
		"LBL_ARMY_OWNED": "Owned: %d",
		"LBL_ARMY_TIER": "Tier %d",
		"LBL_ARMY_POWER_EACH": "Power %d",
		"LBL_ARMY_UPKEEP": "Upkeep %d gold",
		"LBL_ARMY_IN_TRAINING": "In training",
		"BTN_TRAIN": "TRAIN",
		"LBL_ARMY_NO_UNIT": "Unknown unit",
		"LBL_ARMY_NEED_BARRACKS": "Requires a Barracks",
		"LBL_ARMY_LOCKED": "Locked (higher era)",
		"LBL_ARMY_SLOTS_FULL": "Training slots full",
		"LBL_ARMY_AT_CAP": "Army at capacity",
		"LBL_ARMY_EMPTY": "No troops yet. Train units at the Barracks.",
		"NOTIF_UPKEEP_UNPAID": "No gold for the army: %d gold short",

		# Cancelling (Corruption Rate), famine and desertion
		"FMT_CANCEL_REFUND": "Cancel — refunds %s",
		"LBL_CANCEL_NO_REFUND": "Cancel — no refund",
		"LBL_CANCEL_RATE": "Corruption Rate: %d%% comes back",
		"LBL_CANCEL_RATE_STORM": "With the Storm under way only %d%% comes back",
		"FMT_DEMOLISH_IN_PROGRESS": "Something is under way: refunds %s",
		"NOTIF_STARVATION": "Famine: %d citizen dies for lack of supplies.",
		"NOTIF_DESERTION": "Desertion: %d %s walk out of the army unpaid.",

		# Combat / Expeditions
		"BTN_SKIRMISH": "SKIRMISH",
		"BTN_LAUNCH_EXPEDITION": "LAUNCH EXPEDITION",
		"BTN_ABANDON": "Abandon",
		"BTN_END_TURN": "End turn",
		"BTN_DEFEND": "Defend",
		"BTN_WAIT": "Wait",
		"BTN_DEV_SKIRMISH": "Test skirmish",
		"LBL_SKIRMISH_TITLE": "SKIRMISH - EXPEDITION",
		"LBL_DEPLOY_CAP": "Committed: %d / %d",
		"LBL_EXPEDITION_MAP": "Expedition map",
		"LBL_ENCOUNTER_N": "Encounter %d",
		"LBL_BOSS": "BOSS",
		"LBL_TURN_PLAYER": "Your turn",
		"LBL_TURN_ENEMY": "Enemy turn",
		"LBL_ROUND": "Round %d / %d",
		"LBL_DRAFT_TITLE": "Choose an upgrade",
		"LBL_VICTORY": "VICTORY",
		"LBL_DEFEAT": "DEFEAT",
		"LBL_REWARDS": "Spoils",
		"LBL_CASUALTIES": "Casualties",
		"LBL_NO_CASUALTIES": "No losses",
		# The Imperial Storm
		"BTN_REPAIR": "REPAIR",
		"LBL_DAMAGED": "Damaged: %d%% integrity",
		"LBL_RUINED": "IN RUINS - produces nothing",
		"MSG_REPAIR_NOT_NEEDED": "No repair needed",
		"MSG_REPAIR_NO_RESOURCES": "Not enough resources to repair it",
		"NOTIF_BUILDING_RUINED": "%s is in ruins.",
		"STORM_INCOMING_FIRST": "The air is coming in dirty from the east.",
		"STORM_INCOMING": "The east wind again.",
		"STORM_FALSE_ALARM": "The air washes clean. They did not come down this time.",
		"STORM_ASH_STARTED": "Ash begins to fall.",
		"STORM_STARTED": "The storm breaks over the island.",
		"STORM_ENDED": "The air clears.",
		"STORM_TITHE_PAID": "The Assessors have collected the Tithe.",
		"STORM_TITHE_UNDEFENDED": "Nobody left standing. The Assessors collect without stepping down.",
		"STORM_TITHE_DEFENDING": "THE ASSESSORS DEMAND THE TITHE",
		"STORM_TITHE_REPELLED": "The Assessors withdraw with nothing.",
		"STORM_TITHE_TOWER_CREWS": "The towers light their reflectors and man their positions (+%d on the line).",
		"STORM_PHASE_WARNING": "WARNING",
		"STORM_PHASE_ASH": "ASHFALL",
		"STORM_PHASE_STORM": "STORM",
		"STORM_PHASE_TITHE": "TITHE",
		"STORM_TITHE_SEIZED": "Nothing left to pay with: the Assessors seize %d holdings.",
		"STORM_TITHE_CONSCRIPTED": "The books did not balance. They take %d of ours.",
		"STORM_ASH_QUEUE_WARNING": "The ash is a warning: %d in the queue. If the Storm breaks they are lost with their cost (%s).",
		"STORM_ASH_QUEUE_WARNING_FREE": "The ash is a warning: %d mining. If the Storm breaks, the work done is not coming back.",
		"STORM_ASH_TRAINING_WARNING": "The ash is a warning: %d in the barracks. If the Storm breaks they are lost with their cost (%s).",
		"NOTIF_STORM_ATE_PROCESS": "The storm took %s. Its cost is gone: %s.",
		"NOTIF_STORM_ATE_MINING": "The storm buried %s. The work done is gone.",
		"NOTIF_STORM_ATE_TRAINING": "The storm took %s half-trained. Its cost is gone: %s.",
		# The Final Audit
		"AUDIT_TITLE": "THE FINAL AUDIT",
		"AUDIT_SUMMONED": "The Headquarters is finished. The Regency is coming down to audit it.",
		"AUDIT_SUMMONED_DESC": "%d waves are on the way. Whatever garrison is home is what fights.",
		"AUDIT_STARTED": "The audit begins. Nobody gets retrained from here on.",
		"AUDIT_WAVE": "Wave %d of %d",
		"AUDIT_WAVE_CLEARED": "Wave thrown back. %d to go.",
		"AUDIT_LAST_WAVE": "Last wave. They are sending everything they have left.",
		"AUDIT_ATTRITION": "What falls, falls. There are no reliefs.",
		"AUDIT_LOST": "The audit walks straight over you. They take the maximum Tithe and leave.",
		"AUDIT_LOST_DESC": "The game is not lost. Rebuild the army and call them back down.",
		"AUDIT_RESUMMON_LOCKED": "You need %d units standing before you can call them back down.",
		"AUDIT_WON_TITLE": "IMPERIAL VICTORY",
		"AUDIT_WON_BODY": "The Storm stops. For good.",
		"AUDIT_WON_MEANING": "You did not break the system. You inherited it.",
		"AUDIT_WON_LAST_LINE": "The Tithe will be collected on Tuesday.",
		"BTN_AUDIT_BEGIN": "LET THEM COME",
		"BTN_AUDIT_RESUMMON": "CALL THEM BACK DOWN",
		"LBL_MORALE_DELTA": "Morale %+d",
		"LBL_RISK_LOW": "Low risk",
		"LBL_RISK_MED": "Medium risk",
		"LBL_RISK_HIGH": "High risk",
		"LBL_MORALE_COMBAT": "Morale %d: initiative %+d, attack x%.2f",
		"LBL_UNIT_IN_EXPEDITION": "On campaign",
		"MSG_NO_UNITS": "You have no units available for an expedition.",
		"MSG_EXPEDITION_WON": "Expedition complete. Spoils: %s",
		"MSG_EXPEDITION_LOST": "Expedition wiped out. Casualties: %d",
		"MSG_EXPEDITION_ABANDONED": "Expedition abandoned. You keep the spoils.",
		"MSG_CONFIRM_ABANDON": "You will abandon the expedition. You keep the spoils and the survivors.",
		"OBJ_ELIMINATE_ALL": "Eliminate all enemy units",
		"DRAFT_ATK": "Assault doctrine: +%d attack",
		"DRAFT_DEF": "Improvised plating: +%d defense",
		"DRAFT_HP_HEAL": "Field station: heal %d%% health",
		"DRAFT_MOVE": "Reinforced tracks: +%d movement",
		"DRAFT_INIT": "Advance orders: +%d initiative",

		# Building Info extras
		"LBL_POP_CAPACITY": "+%d population",
		"LBL_MORALE_BONUS": "+%d morale",
		"LBL_ROTATE_BUILDING": "Rotate building (R)",

		# Tech bonuses
		"FMT_SPREAD_REDUCTION": "-%d%% spread",
		"FMT_CONSUMPTION_REDUCTION": "-%d%% consumption",
		"FMT_BUILD_SPEED": "+%d%% build speed",

		# Tutorial
		"BTN_TUTORIAL_NEXT": "Next",
		"BTN_TUTORIAL_SKIP": "Skip",
		"BTN_TUTORIAL_START": "Begin",
		"BTN_TUTORIAL_OK": "Got it",
		"LBL_TUTORIAL_PAGE": "%d / %d",
		"LBL_TUTORIAL_SECTION_LORE": "THE WORLD",
		"LBL_TUTORIAL_SECTION_PLAY": "HOW TO PLAY",
		"TUT_INTRO_1_TITLE": "The Empire Without Sunset",
		"TUT_INTRO_1_BODY": "That is what it calls itself: the Empire Without Sunset, the one the sun never sets on.\n\nIt is true. Over them, it never does.\n\nOver us, it has not risen in three generations. We live under a roof of ash they manufacture and dispatch, in a permanent rust-coloured dusk. They divided up the light of the world and kept all of it.\n\nTheir motto: \"Wherever the light reaches\". What it really means: as far as they decide it should.",
		"TUT_INTRO_2_TITLE": "The Perpetual",
		"TUT_INTRO_2_BODY": "The Empire is ruled by the Perpetual, emperor by eternal right.\n\nNo one has seen him in a hundred and fourteen winters. No new portraits. No speeches. There are signatures: thousands upon thousands, all identical, on every tribute order, every sentence and every storm dispatch.\n\nThe Perpetual is dead, and has been for a century.\n\nThey do not hide it out of devotion. They hide it out of arithmetic: announcing a death opens a succession, a succession is a war, and a war interrupts collection. A dead emperor never changes his mind and never forgives a debt. He is the perfect ruler. That is why they keep him.",
		"TUT_INTRO_3_TITLE": "The Regency",
		"TUT_INTRO_3_BODY": "If the emperor does not rule, someone does.\n\nThe Regency was founded as a temporary measure to administer the Empire in the Perpetual's absence. That was a hundred and fourteen winters ago. It is still temporary.\n\nIt is not an army or a court: it is an accounting house. Lifelong clerks who do not conquer territories, they register them. Who do not declare wars, they suspend supplies. Who know exactly how much grain every province holds and how long every province lasts without it.\n\nTheir motto: \"Nothing is lost\". It sounds like comfort. It is an inventory.",
		"TUT_INTRO_4_TITLE": "The Storm is not weather",
		"TUT_INTRO_4_BODY": "People believe the Storm is weather. A punishment of the world, the bad luck of being born downwind. They pray to it. They endure it.\n\nThe Storm is not weather. It is mail.\n\nAcross the ocean stand the Chimneys: an artificial mountain range whose only purpose is to push the air. All the slag of the Empire is loaded onto the wind and dispatched. And it leaves on schedule.\n\nThey do not send it to dirty us. They send it to soften us. With the ash come the Assessors: armed appraisers who look at your stores, write it down and take their share. They call it the Tithe. First the ruin, then the bill. Always in that order.",
		"TUT_INTRO_5_TITLE": "Us: the Written-Off",
		"TUT_INTRO_5_BODY": "They did not defeat us. They wrote us off.\n\nThree generations ago, a clerk we never met made a calculation we never saw and decided this island had stopped being profitable. We appear in the Ledger as an accepted loss. They stopped counting us. And we survived.\n\nWhat is not in the Ledger is not collected. That invisibility was the only good thing that ever happened to us.\n\nBut we have grown. Chimneys can be seen from the sea. And the Regency, which never forgives a miscalculation, has opened the page again.\n\nGrowing is what makes you visible. Being visible is what brings the Storm.",
		"TUT_INTRO_6_TITLE": "On the mud of history",
		"TUT_INTRO_6_BODY": "\"On the mud of history, we shall build monuments of steel.\"\n\nThis is what you have: a Core, three hundred gold, two hundred wood and an island the Empire struck out.\n\nBuild. Grow. And when the air comes in dirty from the east, let it find you ready.\n\nNext: how to play.",
		"TUT_PLAY_1_TITLE": "The Core and the first works",
		"TUT_PLAY_1_BODY": "The Core is your centre. It cannot be demolished and it never falls.\n\nFirst, always: a sawmill. Without wood there is nothing, and everything that follows costs it. Place it right next to a forest: extractors go beside their deposit, just as the gold mine goes beside a vein.\n\nThen a house. Almost every building needs people to run it; without workers it stands idle.\n\nBUILD button at the bottom. WASD or drag to move the camera, wheel to zoom, R to rotate before placing.",
		"TUT_PLAY_2_TITLE": "One single bag",
		"TUT_PLAY_2_BODY": "Your four resources (gold, wood, steel and oil) share ONE single storage bag. When it is full, whatever you produce is lost. Spend, or build warehouses.\n\nYour people eat: each person consumes 1 wood and 1 gold per cycle. If you cannot pay, morale collapses.\n\nMorale multiplies your production: at 0 you produce half, at 100 twenty percent more. When you grow, grow wood first.",
		"TUT_PLAY_3_TITLE": "The Storm can be seen coming",
		"TUT_PLAY_3_BODY": "The Storm does not hit at once. It has phases, and the sky indicator tells you which:\n\nWARNING: ash on the horizon. Nothing falls yet.\nASH: production drops, and whatever is queued will be lost.\nSTORM: it breaks buildings.\nTITHE: the Assessors arrive to collect.\n\nSpend beforehand what you do not want taken. Repair afterwards what broke. And keep a garrison: if the Assessors meet resistance, it is fought on the board, and if you win they take nothing.",
		"TUT_PLAY_4_TITLE": "Towers and garrison",
		"TUT_PLAY_4_BODY": "Standing towers soften the Storm's damage, and their crews fight when the Assessors arrive.\n\nThe Barracks trains units: infantry, artillery and vehicles. Each barracks trains one at a time, and all of them draw wages in gold.\n\nOn the board: a unit moves and then attacks. Artillery cannot fire at an enemy adjacent to it. Defending doubles defence until your next turn.\n\nThe path: sawmill, houses, mine, foundry (era 2), barracks, refinery on an oil well (era 3), towers, Headquarters. At level 3 it summons the Regency's final audit. Survive it.",
		"TUT_TIP_INCOMING_TITLE": "Warning: ash on the horizon",
		"TUT_TIP_INCOMING_BODY": "The air is coming in dirty from the east. Nothing falls yet, but it will.\n\nNow: spend what you do not want taken, repair what is damaged and make sure you have a garrison. The Assessors collect on whatever they find in your stores.",
		"TUT_TIP_ASH_TITLE": "Ash is falling",
		"TUT_TIP_ASH_BODY": "Production drops while it lasts. And beware: running processes and units in training will be lost when the Storm hits. Finish what you can and start nothing new.",
		"TUT_TIP_STORM_TITLE": "Storm",
		"TUT_TIP_STORM_BODY": "Now it breaks buildings. Standing towers soften the damage. A building that reaches zero is left in ruins and stops producing until you repair it. Hold on: it passes.",
		"TUT_TIP_TITHE_TITLE": "The Assessors",
		"TUT_TIP_TITHE_BODY": "They have come to collect the Tithe. Your garrison fights on the board. If you win, they take nothing. If you lose, or have nothing to fight with, they take a percentage of your stores.",
		"TUT_TIP_RUINED_TITLE": "A building in ruins",
		"TUT_TIP_RUINED_BODY": "In ruins it produces nothing. It stays where it is: click the building and press REPAIR. It costs resources, but less than building it again.",
		"TUT_TIP_OVERFLOW_TITLE": "The bag is full",
		"TUT_TIP_OVERFLOW_BODY": "Your four resources share one single bag, and whatever does not fit is lost. Spend on buildings or build a warehouse: each one raises the cap by 500.",
		"TUT_TIP_BOARD_TITLE": "The board",
		"TUT_TIP_BOARD_BODY": "Turn-based, in initiative order. A unit may move and then attack; attacking ends its turn. Artillery cannot fire at an enemy adjacent to it. Defending doubles defence until your next turn.",
	},
}

func t(key: String) -> String:
	return _STRINGS.get(_locale, {}).get(key, key)

func res_name(res_id: String) -> String:
	return _RESOURCES.get(_locale, {}).get(res_id, res_id)

func res_upper(res_id: String) -> String:
	return _RESOURCES_UPPER.get(_locale, {}).get(res_id, res_id)

func res_cap(res_id: String) -> String:
	return _RESOURCES_CAP.get(_locale, {}).get(res_id, res_id)

## Lista legible de cantidades por recurso ({"gold": 21} -> "21 oro").
## Vive aqui porque el nombre del recurso ya es cosa del idioma, y porque el
## reembolso de una cancelacion tiene que leerse igual en los dos paneles.
func amount_list(amounts: Dictionary) -> String:
	var parts: Array = []
	for res_id in amounts:
		parts.append("%d %s" % [int(amounts[res_id]), res_name(res_id)])
	return " | ".join(parts)

func set_locale(locale: String) -> void:
	_locale = locale
